// Code generated by "stringer -type=Diet -output=diet_string.go"; DO NOT EDIT.

package recipe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownDiet-0]
	_ = x[DiabeticDiet-1]
	_ = x[GlutenFreeDiet-2]
	_ = x[HalalDiet-3]
	_ = x[HinduDiet-4]
	_ = x[KosherDiet-5]
	_ = x[LowCalorieDiet-6]
	_ = x[LowFatDiet-7]
	_ = x[LowLactoseDiet-8]
	_ = x[LowSaltDiet-9]
	_ = x[VeganDiet-10]
	_ = x[VegetarianDiet-11]
}

const _Diet_name = "UnknownDietDiabeticDietGlutenFreeDietHalalDietHinduDietKosherDietLowCalorieDietLowFatDietLowLactoseDietLowSaltDietVeganDietVegetarianDiet"

var _Diet_index = [...]uint8{0, 11, 23, 37, 46, 55, 65, 79, 89, 103, 114, 123, 137}

func (i Diet) String() string {
	if i < 0 || i >= Diet(len(_Diet_index)-1) {
		return "Diet(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Diet_name[_Diet_index[i]:_Diet_index[i+1]]
}
